# yaml
name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo layout
        run: |
          pwd
          ls -la
          find . -maxdepth 5 -name pom.xml || true

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Option A: build when `./pom.xml` is at repository root
      - name: Build (repo root)
        run: mvn -B clean verify --batch-mode

      # Option B: build when `pom.xml` is in a subfolder (replace path/to/module)
      #- name: Build (module)
      #  working-directory: path/to/module
      #  run: mvn -B clean verify --batch-mode
      #
      # Or explicitly with -f:
      #- name: Build with -f
      #  run: mvn -B -f path/to/module/pom.xml clean verify --batch-mode
