name: CI Pipeline

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo layout
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name pom.xml || true

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Build (if pom.xml is at repo root)
        run: mvn -B -f ./pom.xml clean verify --batch-mode

      # OR, if pom.xml is in a subfolder e.g. `backend`
      #- name: Build (module)
      #  working-directory: backend
      #  run: mvn -B clean verify --batch-mode
