# yaml
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

                                     
   

      - name: Build and run unit + integration tests
        run: mvn -B clean verify --batch-mode
        # If your pom.xml is NOT at the repository root, uncomment and set the correct relative path:
        # working-directory: path/to/project
